Fix track roomba
Pitt-RAS/iarc7_abstract pull request #22
Opened 2017-09-24 21:07 UTC by Qisgreat

I modified the abstract to test the new features with track_roomba

2017-09-24 21:21 UTC, asaba96 reviewed
Looks good, but PR in iarc7_motion needs merged first

2017-09-24 21:30 UTC, amiller27 commented on scripts/track_roomba.py
> +    goal = QuadMoveGoal(movement_type="track_roomba", frame_id = roomba_id, time_to_track = 5.0, overshoot = .5)
In `iarc7_abstract`, the python convention is no spaces around `=` in named function args

2017-09-24 21:31 UTC, aftersomemath submitted a review, later dismissed

2017-09-24 21:31 UTC, aftersomemath commented on scripts/track_roomba.py
> +    goal = QuadMoveGoal(movement_type="track_roomba", frame_id = roomba_id, time_to_track = 5.0, overshoot = .5)
Check line length?

2017-09-25 15:10 UTC, aftersomemath commented
Note to myself that this needs to be updated to reflect the accompanying changes in the PR in HLM

2017-10-22 21:24 UTC, amiller27 requested changes
Looks good.

One thing, the python convention for named parameters is no spaces around the `=` sign, can you change that where you're making the `QuadMoveGoal` objects?

Also, has the RoombaRequestExecuter been tested in the sim?

2017-10-22 21:41 UTC, Qisgreat commented
Fixed the conventions

2017-10-22 21:42 UTC, amiller27 approved these changes

2017-10-22 21:45 UTC, merged