Hover during takeoff
Pitt-RAS/iarc7_abstract pull request #29
Opened 2017-12-28 22:55 UTC by aftersomemath

2017-12-28 23:20 UTC, amiller27 approved these changes

2017-12-28 23:37 UTC, asaba96 requested changes
Is this how we want to hover? We have a hold position task that will attempt to hold a position. All this is doing is setting the x and y velocity to zero, but will hold a z position. If we use the hold position task, the x and y positions will be held, along with the z.

I can see how doing it with the velocity task can help with debugging velocity controllers in x and y, but long term is this what we want?

2017-12-29 05:35 UTC, aftersomemath commented
Right now it's all the motion coordinator can support and it's trivial to change it later. The alternative to write two scripts. One to support with full position estimates and one that does it the way done in this PR which would be unnecessary in my opinion.

2017-12-29 09:36 UTC, asaba96 approved these changes

2017-12-29 09:37 UTC, asaba96 commented
I agree. It is trivial to change later. Just wanted to make sure we thought about it.

2017-12-29 09:37 UTC, merged